# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Annodoc
baseurl: "/lim-annodoc"
homeurl: "https://github.com/tibetan-nlp/lim-annodoc/"
issueurl: "https://github.com/tibetan-nlp/lim-annodoc/issues"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
  relation:
    output: true

theme: jekyll-theme-tactile
