# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Lexicography in Motion 
#baseurl: ""
baseurl: "/lim-annodoc"
homeurl: "https://github.com/tibetan-nlp/lim-annodoc/"
issueurl: "https://github.com/tibetan-nlp/lim-annodoc/issues"

##############################################################################

# Collection settings

collections:
  dependencies:
    output: true
    permalink: /dependencies/:path/

theme: jekyll-theme-tactile
